# Generated by Django 3.2.9 on 2022-12-31 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_auto_20221225_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_short_description',
        ),
    ]
