# Generated by Django 3.2.9 on 2023-01-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_remove_product_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('posted', 'posted')], max_length=100),
        ),
    ]
