# Generated by Django 3.2.9 on 2023-02-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0004_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Comment', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
