# Generated by Django 3.2.9 on 2023-02-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='comment',
        ),
    ]
