# Generated by Django 3.2.9 on 2023-02-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0009_comment_blog_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog_id',
            new_name='blog',
        ),
    ]
